version: '3.6'

networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    networks:
      bridge:
        aliases:
          - kafka
  
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    environment:
      ZK_HOSTS: "zookeeper:32181"
    ports:
      - 9000:9000
    networks:
      - bridge

  kafka-producer:
    image: kafka-spark-flink-example
    depends_on:
      - kafka
    environment:
      EXAMPLE_GOAL: "producer"
      EXAMPLE_KAFKA_TOPIC: "example"
      EXAMPLE_KAFKA_SERVER: "kafka:9092"
      EXAMPLE_ZOOKEEPER_SERVER: "zookeeper:32181"
      EXAMPLE_PRODUCER_INTERVAL: 10000
      APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      APPDYNAMICS_CONTROLLER_PORT: 8090
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "kafka-spark-flink-example"
      APPDYNAMICS_AGENT_TIER_NAME: "Producer"
      APPDYNAMICS_AGENT_NODE_NAME: "reuse"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "producer-node"
    networks:
      - bridge

  kafka-consumer-flink:
    image: kafka-spark-flink-example
    depends_on:
      - kafka-producer
    environment:
      EXAMPLE_GOAL: "consumer.flink"
      EXAMPLE_KAFKA_TOPIC: "example"
      EXAMPLE_KAFKA_SERVER: "kafka:9092"
      EXAMPLE_ZOOKEEPER_SERVER: "zookeeper:32181"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      APPDYNAMICS_CONTROLLER_PORT: 8090
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "kafka-spark-flink-example"
      APPDYNAMICS_AGENT_TIER_NAME: "Flink-Consumer"
      APPDYNAMICS_AGENT_NODE_NAME: "reuse"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "flink-consumer-node"
    networks:
      - bridge

  #kafka-consumer-kafka:
    #image: kafka-spark-flink-example
    #depends_on:
      #- kafka-producer
    #environment:
      #EXAMPLE_GOAL: "consumer.kafka"
      #EXAMPLE_KAFKA_TOPIC: "example"
      #EXAMPLE_KAFKA_SERVER: "kafka:9092"
      #EXAMPLE_ZOOKEEPER_SERVER: "zookeeper:32181"
      #APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      #APPDYNAMICS_CONTROLLER_PORT: 8090
      #APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      #APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      #APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      #APPDYNAMICS_AGENT_APPLICATION_NAME: "kafka-spark-flink-example"
      #APPDYNAMICS_AGENT_TIER_NAME: "Kafka-Consumer"
      #APPDYNAMICS_AGENT_NODE_NAME: "reuse"
      #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "kafka-consumer-node"
    #networks:
      #- bridge

  #kafka-consumer-spark:
    #image: kafka-spark-flink-example
    #depends_on:
      #- kafka-producer
    #ports:
      #- 4040:4040
    #environment:
      #EXAMPLE_GOAL: "consumer.spark"
      #EXAMPLE_KAFKA_TOPIC: "example"
      #EXAMPLE_KAFKA_SERVER: "kafka:9092"
      #EXAMPLE_ZOOKEEPER_SERVER: "zookeeper:32181"
      #APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      #APPDYNAMICS_CONTROLLER_PORT: 8090
      #APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      #APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      #APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      #APPDYNAMICS_AGENT_APPLICATION_NAME: "kafka-spark-flink-example"
      #APPDYNAMICS_AGENT_TIER_NAME: "Spark-Consumer"
      #APPDYNAMICS_AGENT_NODE_NAME: "reuse"
      #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      #APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "spark-consumer-node"
    #networks:
      #- bridge